import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  title: 'Mr.Pizza',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-300 h-full">{children}</body>
    </html>
  )
}
